contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
	path('', views.index, name='index'),
	path('sent', views.sendContact, name="send_contact"),
]

faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
	path('', views.index, name='index'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.index, name='index'),
	path('sitemap.xml', views.site_map, name='site_map'),
]

rfq/urls.py
from django.urls import path
from . import views

app_name = 'rfq'

urlpatterns = [
	path('', views.index, name='index'),
	path('quoted', views.quoted, name='quoted'),
	path('record', views.record, name='record'),
]

rfq/models.py
from django.db import models

# Create your models here.

from django.utils import timezone

import datetime

class Quote(models.Model):
	address = models.CharField(max_length=200, default='')
	city = models.CharField(max_length=50, default='')
	state = models.CharField(max_length=20, default='')
	zipcode = models.CharField(max_length=10, default='')
	timestamp = models.DateTimeField()
	email = models.CharField(max_length=50, default='')
	price = models.IntegerField(default=0)
	options = models.CharField(max_length=200, default='')
	scheduled = models.BooleanField(default=False)

	def __str__(self):
		return self.email + ' | ' + str(self.timestamp)

	# Define regression for getting quote price
	def getPrice(self, sqft=0, year_built=0, home_value=0, unit_type=''):

		age = 2020-year_built
		quoted_price = 0

		cost_sqfoot = 400 + max(0,(sqft-3000)*0.1)
		cost_radon = 150
		cost_termite = 100
		cost_mold = 425
		cost_well = 100
		cost_pool = 150
		cost_age = age*0.5
		cost_value = home_value / 8000.0

		if 'base-inspect' in self.options:
			if 'APT' in str(unit_type):
				quoted_price += 250
			else:
				quoted_price += cost_sqfoot
		if 'radon' in self.options:
			quoted_price += cost_radon
		if 'termite' in self.options:
			quoted_price += cost_termite
		if 'mold' in self.options:
			quoted_price += cost_mold
		if 'well' in self.options:
			quoted_price += cost_well
		if 'pool' in self.options:
			quoted_price += cost_pool

		quoted_price += cost_age + cost_value

		self.price = int(quoted_price)

rfq/views.py
from django.shortcuts import render, get_object_or_404
from .models import Quote 
from django.utils import timezone
from django.core.mail import send_mail
from mysite.settings import EMAIL_HOST_USER
import requests

# Create your views here.
def index(request):
	return render(request, 'rfq/quotepage.html')

def quoted(request):
	options = ['base-inspect', 'radon', 'termite', 'mold', 'well', 'pool']
	#fetch form information out of the request
	#need to throw error if page accessed directly, i.e. no POST request
	try:
		address = request.POST['address']
		city = request.POST['city']
		state = request.POST['state']
		zipcode = request.POST['zip']
		email = request.POST['email']
		timestamp = timezone.now()
		quote_options = ''

		for option in options:
			if option in request.POST:
				quote_options+= option + ', '

	except KeyError:
		return render(request, 'rfq/quotepage.html')

	quote = Quote(address=address, 
				  city=city, 
				  state=state, 
				  zipcode=zipcode,
				  email=email, 
				  timestamp=timestamp,
				  options=quote_options)

	# endpoint = 'https://sandbox.estated.com/v4/property?' #sandbox
	endpoint = 'https://apis.estated.com/v4/property?' #production
	# token = 'HrKD9Ef6Rot4Yb9rxeDAfZdWKCiofs' #sandbox
	token = '' #production
	endpoint += 'token=' + token + '&combined_address='


	endpoint += address + ', ' + city + ', ' + state + ' ' + zipcode

	response = requests.get(endpoint)
	
	try:
		yr_built = response.json()['data']['structure']['year_built']
		sqft = response.json()['data']['structure']['total_area_sq_ft']
		home_value = response.json()['data']['valuation']['value']
		unit_type = response.json()['data']['address']['unit_type']

	except TypeError:
		error_message = "Sorry, we couldn't find that property. Try quoting again."
		return render(request, 'rfq/error.html', {'error' : error_message,})
	
	quote.getPrice(sqft=sqft, year_built=yr_built, home_value=home_value, unit_type=unit_type)
	quote.save()
	send_mail('New quote from ' + email, str(quote), EMAIL_HOST_USER, [EMAIL_HOST_USER])

	return render(request, 'rfq/quoted.html', {
		'quote': quote,
	})

def record(request):
	try:
		quote_id = request.POST['quote_id']

	except KeyError:
		error_message = "Sorry, something went wrong in trying to schedule that quote. Please try again."
		return render(request, 'rfq/error.html', {'error' : error_message})

	quote = get_object_or_404(Quote, pk=quote_id)

	send_mail('New request to schedule inspection', 'Quote ID = ' + str(quote_id), EMAIL_HOST_USER, [EMAIL_HOST_USER])
	quote.scheduled=True
	quote.save()
	return render(request, 'rfq/record.html')

rfq/templates/rfq/error.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="RB Companies, LLC">
    <title>Inspecty - Free and Instant Home Inspection Quote</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta name="theme-color" content="#563d7c">

    <!--Favicons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'homepage/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'homepage/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'homepage/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'homepage/images/site.webmanifest' %}">
  	<link rel="stylesheet" href="{% static 'contact/css/contactstyle.css' %}">

  </head>
  <body class="bg-light">
    <div class="container">

    <header class="masthead mb-auto">
      <div class="inner">
        <nav class="nav nav-masthead justify-content-center">
          <a class="nav-link" href="/">Home</a>
          <a class="nav-link active" href="/rfq">Quote</a>
          <a class="nav-link" href="/about">About</a>
          <a class="nav-link" href="/faq">FAQ</a>
          <a class="nav-link" href="/blog">Blog</a>


        </nav>
      </div>
    </header>

  <div class="py-5 text-center">
	<a href="{% url 'homepage:index' %}">
	<img class= "d-block mx-auto mb-4" src="{% static 'homepage/images/logo_homes.png' %}" width="291" height="170">
	</a>
    <h5>{{ error }}<h5>
  </div> 
  
<br><br><br><br><br><br>
  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2020 RBCo</p>
  </footer>
</div>
<!-- 
Insert bootstraps JS dependencies -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

rfq/templates/rfq/quotepage.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-167548724-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-167548724-1');
    </script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Free and instant home inspection quote form.">
    <meta name="author" content="RB Companies, LLC">
    <title>Inspecty Homes - Instant Quote</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta name="theme-color" content="#563d7c">
      <!--Favicons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'homepage/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'homepage/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'homepage/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'homepage/images/site.webmanifest' %}">

  	<link rel="stylesheet" href="{% static 'rfq/css/quotestyles.css' %}">

  </head>
  <body class="bg-light">
    <div class="container">

      <header class="masthead mb-auto">
        <div class="inner">
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link" href="/">Home</a>
            <a class="nav-link active" href="/rfq">Quote</a>
            <a class="nav-link" href="/about">About</a>
            <a class="nav-link" href="/faq">FAQ</a>
            <a class="nav-link" href="/blog">Blog</a>


          </nav>
        </div>
      </header>

  <div class="py-5 text-center">
  	<a href="{% url 'homepage:index' %}">
  	<img class= "d-block mx-auto mb-4" src="{% static 'homepage/images/logo_homes.png' %}" alt="" width="291" height="170">
  	</a>
    <h4 class="left">Free Inspection Quote</h4>
  </div> 
  
  <!-- Start Form  -->
  <div class="col-md-8 order-md-1 up">
      <form action="{% url 'rfq:quoted' %}" method="post" class="needs-validation" novalidate>
      {% csrf_token %}

        <div class="mb-3">
          <label for="address">Address</label>
          <input type="text" class="form-control" id="address" name="address" required>
          <div class="invalid-feedback">
            Please enter your address.
          </div>
        </div>

        <div class="row">
		      <div class="col-md-4 mb-3">
            <label for="city">City</label>
            <input type="text" class="form-control" id="city" name="city" required>
            <div class="invalid-feedback">
              Please enter your city.
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="state">State</label>
            <select class="custom-select d-block w-100" id="state" name="state" required>
              <option value="">Choose...</option>
              <option>AL</option>
              <option>AK</option>
              <option>AZ</option>
              <option>AR</option>
              <option>CA</option>
              <option>CO</option>
              <option>CT</option>
              <option>DE</option>
              <option>FL</option>
              <option>GA</option>
              <option>HI</option>
              <option>ID</option>
              <option>IL</option>
              <option>IN</option>
              <option>IA</option>
              <option>KS</option>
              <option>KY</option>
              <option>LA</option>
              <option>ME</option>
              <option>MD</option>
              <option>MA</option>
              <option>MI</option>
              <option>MN</option>
              <option>MS</option>
              <option>MO</option>
              <option>MT</option>
              <option>NE</option>
              <option>NV</option>
              <option>NH</option>
              <option>NJ</option>
              <option>NM</option>
              <option>NY</option>
              <option>NC</option>
              <option>ND</option>
              <option>OH</option>
              <option>OK</option>
              <option>OR</option>
              <option>PA</option>
              <option>RI</option>
              <option>SC</option>
              <option>SD</option>
              <option>TN</option>
              <option>TX</option>
              <option>UT</option>
              <option>VT</option>
              <option>VA</option>
              <option>WA</option>
              <option>WV</option>
              <option>WI</option>
              <option>WY</option>
            </select>
            <div class="invalid-feedback">
              Please provide a valid state.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="zip">Zip Code</label>
            <input type="text" class="form-control" id="zip" name="zip" placeholder="" required>
            <div class="invalid-feedback">
              Zip code required.
            </div>
          </div>
        </div>

          <div class="mb-3">
            <label for="email">Email <span class="text-muted"></span></label>
            <input type="email" class="form-control" id="email" name="email" placeholder="" required>
            <div class="invalid-feedback">
              Please enter a valid email address.
            </div>
          </div>
          <hr class="mb-4">
       		<div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="base-inspect" name="base-inspect" value="True" checked>
            <label class="custom-control-label" for="base-inspect">Base Inspection</label>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="radon" name="radon" value="True">
            <label class="custom-control-label" for="radon">Radon Test</label>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="termite" name="termite" value="True">
            <label class="custom-control-label" for="termite">Termite Inspection</label>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="mold" name="mold" value="True">
            <label class="custom-control-label" for="mold">Mold Screening</label>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="well" name="well" value="True">
            <label class="custom-control-label" for="well">Well Flow Test</label>
          </div>
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="pool" name="pool" value="True">
            <label class="custom-control-label" for="pool">Pool Inspection</label>
          </div>

          <hr class="mb-4">

        </div>
        <button class="btn btn-primary btn-lg btn-block" type="submit">Get Quote</button>
      </form>
    </div>
  </div>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2020 RBCo</p>
    <!--
    <ul class="list-inline">
      <li class="list-inline-item"><a href="{% url 'homepage:index' %}">Home</a></li>
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>-->
  </footer>
</div>

<!-- 
Insert bootstraps JS dependencies -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{% static 'rfq/js/validation.js' %}"></script>
</body>
</html>

rfq/templates/rfq/test.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Inspectee | Quote Request</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/checkout/">

    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .container {
  		max-width: 960px;
		}

	  .lh-condensed { line-height: 1.25; }
    </style>
  </head>
<body>
<p>sup guys</p>
{% load static %}
<img src="{% static 'rfq/images/logo.jpg' %}">
</body>
</html>

rfq/templates/rfq/test2.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Ross Basri">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Inspecty | Instant Quote</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--Favicons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'homepage/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'homepage/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'homepage/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'homepage/images/site.webmanifest' %}">

    <meta name="theme-color" content="#563d7c">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .invoice-box {
        max-width: 800px;
        margin: auto;
        padding: 30px;
        border: 1px solid #eee;
        box-shadow: 0 0 10px rgba(0, 0, 0, .15);
        font-size: 16px;
        line-height: 24px;
        font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color: #555;
      }
    
      .invoice-box table {
        width: 100%;
        line-height: inherit;
        text-align: left;
      }
    
    .invoice-box table td {
        padding: 5px;
        vertical-align: top;
    }
    
    .invoice-box table tr td:nth-child(2) {
        text-align: right;
    }
    
    .invoice-box table tr.top table td {
        padding-bottom: 20px;
    }
    
    .invoice-box table tr.top table td.title {
        font-size: 45px;
        line-height: 45px;
        color: #333;
    }
    
    .invoice-box table tr.information table td {
        padding-bottom: 40px;
    }
    
    .invoice-box table tr.heading td {
        background: #eee;
        border-bottom: 1px solid #ddd;
        font-weight: bold;
    }
    
    .invoice-box table tr.details td {
        padding-bottom: 20px;
    }
    
    .invoice-box table tr.item td{
        border-bottom: 1px solid #eee;
    }
    
    .invoice-box table tr.item.last td {
        border-bottom: none;
    }
    
    .invoice-box table tr.total td:nth-child(2) {
        border-top: 2px solid #eee;
        font-weight: bold;
    }
    
    @media only screen and (max-width: 600px) {
        .invoice-box table tr.top table td {
            width: 100%;
            display: block;
            text-align: center;
        }
        
        .invoice-box table tr.information table td {
            width: 100%;
            display: block;
            text-align: center;
        }
    }
    
    /** RTL **/
    .rtl {
        direction: rtl;
        font-family: Tahoma, 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
    }
    
    .rtl table {
        text-align: right;
    }
    
    .rtl table tr td:nth-child(2) {
        text-align: left;
    }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'rfq/css/style.css' %}" rel="stylesheet">
  </head>

  <body>
   <header class="masthead mb-auto">
    <div class="inner">
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
        <a class="nav-link" href="/about">About</a>
        <a class="nav-link active" href="/rfq">Quote</a>
        <a class="nav-link" href="{% url 'contact:index' %}">Contact</a>
      </nav>
    </div>
  </header>

<!--     <div class="py-5 text-center">
      <a href="{% url 'homepage:index' %}">
      <img class= "d-block mx-auto mb-4" src="{% static 'rfq/images/logo3.png' %}" alt="" width="380" height="105">
      </a>
      <h2>Instant Quote for {{ quote.address }}</h2>

    </div> -->

<!-- <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
</div> -->

<!-- <div class="container">
  <div class="card-deck mb-3 text-center">
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Basic</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">${{ quote.price }}</h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>-Schedule at your convenience</li>
          <li>-NACHI certified inspectors</li>
          <li>-Help center and support</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Choose Basic</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Advanced</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$500</h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>-Basic inspection</li>
          <li>-Radon inspection</li>
          <br>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Choose Advanced</button>
      </div>
    </div>
    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Complete</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$700</h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>-Basic Inspection</li>
          <li>-Radon inspection</li>
          <li>-Feature 3</li>
        </ul>
        <button type="button" class="btn btn-lg btn-block btn-primary">Choose Complete</button>
      </div>
    </div>
  </div> -->
<div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                                <img src="https://www.sparksuite.com/images/logo.png" style="width:100%; max-width:300px;">
                            </td>
                            
                            <td>
                                Invoice #: 123<br>
                                Created: January 1, 2015<br>
                                Due: February 1, 2015
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                Sparksuite, Inc.<br>
                                12345 Sunny Road<br>
                                Sunnyville, CA 12345
                            </td>
                            
                            <td>
                                Acme Corp.<br>
                                John Doe<br>
                                john@example.com
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="heading">
                <td>
                    Payment Method
                </td>
                
                <td>
                    Check #
                </td>
            </tr>
            
            <tr class="details">
                <td>
                    Check
                </td>
                
                <td>
                    1000
                </td>
            </tr>
            
            <tr class="heading">
                <td>
                    Item
                </td>
                
                <td>
                    Price
                </td>
            </tr>
            
            <tr class="item">
                <td>
                    Website design
                </td>
                
                <td>
                    $300.00
                </td>
            </tr>
            
            <tr class="item">
                <td>
                    Hosting (3 months)
                </td>
                
                <td>
                    $75.00
                </td>
            </tr>
            
            <tr class="item last">
                <td>
                    Domain name (1 year)
                </td>
                
                <td>
                    $10.00
                </td>
            </tr>
            
            <tr class="total">
                <td></td>
                
                <td>
                   Total: $385.00
                </td>
            </tr>
        </table>
    </div>
 <footer class="my-5 pt-5 text-muted text-center text-small">
    <div class="inner">
      <p class="mb-1"> &copy; RBCo 2020</p>
    </div>
 </footer>
</div>
</body>
</html>