contact/urls.py
from django.urls import path
from . import views

app_name = 'contact'

urlpatterns = [
	path('', views.index, name='index'),
	path('sent', views.sendContact, name="send_contact"),
]

faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
	path('', views.index, name='index'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.index, name='index'),
	path('sitemap.xml', views.site_map, name='site_map'),
]

contact/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from mysite.settings import EMAIL_HOST_USER

# Create your views here.

def index(request):
	return render(request, 'contact/contact.html')

def sendContact(request):
	try:
		email = request.POST['email']
		comments = request.POST['comments']

	except KeyError:
		return render(request, 'contact/contact.html')

	else:
		send_mail('New Contact from ' + email, comments, EMAIL_HOST_USER, [EMAIL_HOST_USER])

		return render(request, 'contact/success.html')

contact/templates/contact/contact.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Ross Basri">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Inspecty | Contact</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

      <!--Favicons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'homepage/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'homepage/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'homepage/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'homepage/images/site.webmanifest' %}">
    <meta name="theme-color" content="#563d7c">

  	<link rel="stylesheet" href="{% static 'contact/css/contactstyle.css' %}">

  </head>
  <body class="bg-light">
    <div class="container">

  <header class="masthead mb-auto">
    <div class="inner">
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link" href="/">Home</a>
        <a class="nav-link" href="/rfq">Quote</a>
        <a class="nav-link" href="/about">About</a>
        <a class="nav-link" href="/faq">FAQ</a>
        <a class="nav-link" href="/blog">Blog</a>


      </nav>
    </div>
  </header>

  <div class="py-5 text-center">
	<a href="{% url 'homepage:index' %}">
	<img class= "d-block mx-auto mb-4" src="{% static 'homepage/images/logo_homes.png' %}" width="291" height="170">
	</a>
  </div> 
  <h5 class="left"> Send us a message, we'd love to hear from you.</h5>
  
  <!-- Start Form  -->
  <div class="col-md-8 order-md-1 up">
      <form action="{% url 'contact:send_contact' %}" method="post" class="needs-validation" novalidate>
      {% csrf_token %}

        <div class="mb-3">
          <label for="email">Email<span class="text-muted"></span></label>
          <input type="email" class="form-control" id="email" name="email" placeholder="" required>
          <div class="invalid-feedback">
            Please enter a valid email address.
          </div>
        </div>

		<div class="mb-3">
          <label for="comments">Comments<span class="text-muted"></span></label>
          <textarea class="form-control" id="comments" name="comments" rows="5" required></textarea>
          <div class="invalid-feedback">
            Please enter your comments.
          </div>
        </div>
   <!-- Save checkbox maybe to use later for something     
   		<div class="custom-control custom-checkbox">
          <input type="checkbox" class="custom-control-input" id="save-info">
          <label class="custom-control-label" for="save-info">Save this information for next time</label>
        </div> -->
        <hr class="mb-4">

        </div>
        <button class="btn btn-primary btn-lg" type="submit">Send</button>
      </form>
    </div>
  </div>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2020 RBCo</p>
    <!--
    <ul class="list-inline">
      <li class="list-inline-item"><a href="{% url 'homepage:index' %}">Home</a></li>
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>-->
  </footer>
</div>
<!-- 
Insert bootstraps JS dependencies -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{% static 'rfq/js/validation.js' %}"></script>
</body>
</html>

contact/templates/contact/success.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Ross Basri">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Inspecty | Contact</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta name="theme-color" content="#563d7c">

    <!--Favicons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'homepage/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'homepage/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'homepage/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'homepage/images/site.webmanifest' %}">
  	<link rel="stylesheet" href="{% static 'contact/css/contactstyle.css' %}">

  </head>
  <body class="bg-light">
    <div class="container">

    <header class="masthead mb-auto">
      <div class="inner">
        <nav class="nav nav-masthead justify-content-center">
          <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
          <a class="nav-link" href="/about">About</a>
          <a class="nav-link" href="/rfq">Quote</a>
          <a class="nav-link active" href="/contact">Contact</a>
          <a class="nav-link" href="/faq">FAQ</a>

        </nav>
      </div>
    </header>

  <div class="py-5 text-center">
	<a href="{% url 'homepage:index' %}">
	<img class= "d-block mx-auto mb-4" src="{% static 'homepage/images/logo_homes.png' %}" width="324" height="189">
	</a>
    <h5>Your message has been sent successfully! We'll get right back to you.<h3>
  </div> 
  

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2020 RBCo</p>
  </footer>
</div>
<!-- 
Insert bootstraps JS dependencies -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>