faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
	path('', views.index, name='index'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.index, name='index'),
	path('sitemap.xml', views.site_map, name='site_map'),
]

onboard/urls.py
from django.urls import path
from . import views

app_name = 'onboard'

urlpatterns = [
	path('', views.index, name='index'),
	path('success', views.submitOnboard, name='submit_onboard'),
]

onboard/models.py
from django.db import models
import datetime
# Create your models here.

class Partner(models.Model):
	fname = models.CharField(max_length=50)
	lname = models.CharField(max_length=50)
	address = models.CharField(max_length=200)
	city = models.CharField(max_length=50)
	state = models.CharField(max_length=20)
	zipcode = models.CharField(max_length=10)
	email = models.CharField(max_length=50)
	phone_number = models.CharField(max_length=15)	
	timestamp = models.DateTimeField()

	def __str__(self):
		return self.fname + ' ' + self.lname

onboard/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Partner
from django.core.mail import send_mail
from mysite.settings import EMAIL_HOST_USER


def index(request):
	return render(request, 'onboard/onboard.html')

def submitOnboard(request):
	try:
		fname = request.POST['fname']
		lname = request.POST['lname']
		address = request.POST['address']
		city = request.POST['city']
		state = request.POST['state']
		zipcode = request.POST['zip']
		email = request.POST['email']
		phone_number = request.POST['phone_number']
		timestamp = timezone.now()

	except KeyError:
		return render(request, 'onboard/onboard.html')

	else:
		partner = Partner(
				fname=fname,
				lname=lname,
				address=address, 
				city=city, 
				state=state, 
				zipcode=zipcode,
				email=email, 
				phone_number=phone_number,
				timestamp=timestamp)
		partner.save()
		send_mail('New onboard request', str(partner), EMAIL_HOST_USER, [EMAIL_HOST_USER])

		return render(request, 'onboard/success.html')

onboard/templates/onboard/onboard.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
      <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-167548724-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-167548724-1');
    </script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="For home inspectors, enter information here to join our network as a partner.">
    <meta name="author" content="RB Companies, LLC">
    <title>Inspecty - Join Our Network</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

      <!--Favicons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'homepage/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'homepage/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'homepage/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'homepage/images/site.webmanifest' %}">
    <meta name="theme-color" content="#563d7c">

  	<link rel="stylesheet" href="{% static 'onboard/css/onboardstyle.css' %}">

  </head>
  <body class="bg-light">
    <div class="container">

      <header class="masthead mb-auto">
        <div class="inner">
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link" href="/">Home</a>
            <a class="nav-link" href="/rfq">Quote</a>
            <a class="nav-link" href="/about">About</a>
            <a class="nav-link" href="/faq">FAQ</a>
            <a class="nav-link" href="/blog">Blog</a>


          </nav>
        </div>
      </header>

      <div class="py-5 text-center">
      	<a href="{% url 'homepage:index' %}">
      	<img class= "d-block mx-auto mb-4" src="{% static 'homepage/images/logo_homes.png' %}" width="291" height="170">
      	</a>
        <h5>We're very excited to partner with you! <br>Please enter some contact details below to begin the onboarding process.<h5>
      </div> 
  
    <!-- Start Form  -->
    <div class="col-md-8 order-md-1">
      <form action="{% url 'onboard:submit_onboard' %}" method="post" class="needs-validation" novalidate>
      {% csrf_token %}

        
        <div class="row">
          <div class="col-md-4 mb-3">
            <label for="city">First Name</label>
            <input type="text" class="form-control" id="fname" name="fname" required>
            <div class="invalid-feedback">
              Please enter your first name.
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="lname">Last Name</label>
            <input type="text" class="form-control" id="lname" name="lname" placeholder="" required>
            <div class="invalid-feedback">
              Please enter your last name.
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="phone_number">Phone Number</label>
            <input type="text" class="form-control" id="phone_number" name="phone_number" placeholder="" required>
            <div class="invalid-feedback">
              Please enter your phone number.
            </div>
          </div>
        </div>
        <div class="mb-3">
          <label for="address">Address</label>
          <input type="text" class="form-control" id="address" name="address" required>
          <div class="invalid-feedback">
            Please enter your address.
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 mb-3">
            <label for="city">City</label>
            <input type="text" class="form-control" id="city" name="city" required>
            <div class="invalid-feedback">
              Please enter your city.
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="state">State</label>
            <select class="custom-select d-block w-100" id="state" name="state" required>
              <option value="">Choose...</option>
              <option>New Jersey</option>
            </select>
            <div class="invalid-feedback">
              Please provide a valid state.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="zip">Zip Code</label>
            <input type="text" class="form-control" id="zip" name="zip" placeholder="" required>
            <div class="invalid-feedback">
              Zip code required.
            </div>
          </div>
        </div>

          <div class="mb-3">
          <label for="email">Email <span class="text-muted"></span></label>
          <input type="email" class="form-control" id="email" name="email" placeholder="" required>
          <div class="invalid-feedback">
            Please enter a valid email address.
          </div>
        </div>
        <hr class="mb-4">

        </div>
        <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
      </form>
    </div>
  </div>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2020 RBCo</p>
  </footer>
</div>
<!-- 
Insert bootstraps JS dependencies -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{% static 'rfq/js/validation.js' %}"></script>
</body>
</html>

onboard/templates/onboard/success.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="RB Companies, LLC">
    <title>Inspecty - Join Our Network</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <meta name="theme-color" content="#563d7c">

    <!--Favicons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'homepage/images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'homepage/images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'homepage/images/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'homepage/images/site.webmanifest' %}">
  	<link rel="stylesheet" href="{% static 'contact/css/contactstyle.css' %}">

  </head>
  <body class="bg-light">
    <div class="container">

    <header class="masthead mb-auto">
      <div class="inner">
        <nav class="nav nav-masthead justify-content-center">
          <a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
          <a class="nav-link" href="/about">About</a>
          <a class="nav-link" href="/rfq">Quote</a>
          <a class="nav-link" href="/contact">Contact</a>
          <a class="nav-link" href="/faq">FAQ</a>


        </nav>
      </div>
    </header>

  <div class="py-5 text-center">
	<a href="{% url 'homepage:index' %}">
	<img class= "d-block mx-auto mb-4" src="{% static 'homepage/images/logo_homes.png' %}" width="291" height="170">
	</a>
    <h5>We've received your contact info and will be in touch shortly about onboarding! <h3>
  </div> 
  

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2020 RBCo</p>
  </footer>
</div>
<!-- 
Insert bootstraps JS dependencies -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>